# Generated by Django 5.2.7 on 2025-11-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=100)),
                ('is_working', models.BooleanField(default=False)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='emp.department')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
